name: Django DRF T_E_T

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run Flake8
        run: poetry run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwerty123456
          POSTGRES_DB: T_E_T
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Makemigrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: T_E_T
          USER: postgres
          PASSWORD: qwerty123456
          HOST: localhost
          PORT: 5432
        run: poetry run python manage.py makemigrations
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: T_E_T
          USER: postgres
          PASSWORD: qwerty123456
          HOST: localhost
          PORT: 5432
        run: poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop/C_W_F'
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Copy project files to server
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          DEPLOY_DIR="${{ secrets.DEPLOY_DIR }}"
          if [ ! -d "\$DEPLOY_DIR/.git" ]; then
            echo "Cloning repository into \$DEPLOY_DIR..."
            git clone "https://github.com/YURIi454/T_E_T" "\$DEPLOY_DIR"
          fi
          cd "\$DEPLOY_DIR"
          git fetch origin
          git checkout "develop/tet"
          git reset --hard "origin/develop/tet"
          EOF
      - name: Install dependencies on server
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          curl -sSL https://install.python-poetry.org | python3 -
          ~/.local/bin/poetry install --no-root
          EOF
      - name: Setup and configure PostgreSQL
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          sudo apt update
          
          sudo apt install -y postgresql postgresql-contrib
          
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          
          sudo systemctl status postgresql
          
          if ! systemctl is-active --quiet postgresql; then
            echo "PostgreSQL is not running. Starting..."
            sudo systemctl start postgresql
          else
            echo "PostgreSQL is already running."
          fi
          sudo systemctl enable postgresql
          sudo -u postgres psql -c "ALTER USER ${{ secrets.POSTGRES_USER }} WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"
          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${{ secrets.POSTGRES_NAME }}';" | grep -q 1 || \
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_NAME }} OWNER ${{ secrets.POSTGRES_USER }};"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.POSTGRES_NAME }} TO ${{ secrets.POSTGRES_USER }};"
          EOF
      - name: Create .env file on server
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          cat > .env <<EOL
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          NAME=${{ secrets.POSTGRES_NAME }}
          USER=${{ secrets.POSTGRES_USER }}
          PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          HOST=localhost
          PORT=5432
          EOL
          EOF
      - name: Apply migrations
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          PGPASSWORD='${{ secrets.POSTGRES_PASSWORD }}' psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_NAME }} -c "SELECT 1;" || exit 1
          ~/.local/bin/poetry run python manage.py migrate --no-input
          EOF
      - name: Start Django application
        run: |
          # Старт проекта
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          pkill -f "gunicorn config.wsgi:application" || true
          nohup ~/.local/bin/poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 > app.log 2>&1 &
          echo "Application started in background"
          EOF